name: build-and-push
on:
  workflow_dispatch:
jobs:
  trigger:
    timeout-minutes: 30
    runs-on: ubuntu-24.04-32c
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container image
        run: |
          repo=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tag=${{ github.event.release.tag_name || github.sha }}
          url=${repo,,}:$tag
          cd docker/
          docker build . -t $url --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -f ./Dockerfile.base
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push $url
